Fwxv 134 create pedal main task
uw-midsun/fwxv pull request #105
Opened 2022-10-29 18:31 UTC by Scrubpai

2022-10-30 00:10 UTC, Bafran requested changes
Overall looks good! For the whole main.c file, go through the unimplemented functions and just make sure there's a TODO comment explaining what it is as well. Also, `can.c`, `generator.py`, and `_rx_all.c.jinja` don't need to be included in this PR, so revert those changes and make sure the only three files changed are within the pedal project.

2022-10-30 00:10 UTC, Bafran commented on projects/pedal/src/main.c
> +  if (read_pedal_brake()) {
We can consolidate this a bit, when brake is not pressed is the only time we have to send proper throttle data, so we can do something like
```
if (!read_pedal_brake()) { ... }
else { /* Send throttle data with brake as 0 */ }
```
also, throttle will be sent as per the reading from `read_throttle_data` so that should be changed from a bool to instead return an `uint16_t`.

2022-10-30 00:10 UTC, Bafran commented on projects/pedal/src/main.c
> +  .device_id = 0x1,
This might end up changing again but leave the device id as 0x06 for now

2022-10-30 00:10 UTC, Bafran commented on projects/pedal/src/main.c
> +// #include "event_queue.h"
You can get rid of `#include "event_queue.h"`

2022-11-02 05:03 UTC, mitchellostler commented on projects/pedal/src/main.c
> +  .device_id = 0x1,
This is actually defined in `./libraries/ms-common/inc/can_board_ids.h` as SYSTEM_CAN_DEVICE_PEDAL

2022-11-02 05:03 UTC, mitchellostler commented on can/src/can.c
> -  } else if (msg->id.msg_id >= CAN_MSG_MAX_IDS) {
Was there a reason for this being removed?

2022-11-02 15:59 UTC, Bafran commented on can/src/can.c
> -  } else if (msg->id.msg_id >= CAN_MSG_MAX_IDS) {
Yeah, I was going to bring this up to Jarvis today, the linter sees this as a case that will never be hit because of the sizes of `msg->id.msg_id` and `CAN_MSG_MAX_IDS`. I assume the fix shouldn't be included in this PR though

2022-11-07 19:48 UTC, JarvisWeng approved these changes
Yeah I'm good with it. The `calib` can be another ticket I guess then

2022-11-07 20:10 UTC, Bafran approved these changes

2022-11-07 22:58 UTC, merged