Fwxv 138 steering steering digital task
uw-midsun/fwxv pull request #114
Opened 2022-11-24 01:16 UTC by Citrusboa

2022-11-25 03:30 UTC, Kyle02 requested changes
Looks good, just some minor changes needed.

2022-11-25 03:30 UTC, Kyle02 commented on projects/steering/src/steering_digital_task.c
> +StatusCode steering_digital_input_init(void) {
Do you set any initial values for the different signals? They should probably be set to some default so that your functions are pulling a NULL input.

2022-11-25 03:30 UTC, Kyle02 commented on projects/steering/src/steering_digital_task.c
> +        set_digital_signal_cruise_control_command(CRUISE_CONTROL_COMMAND |
000 | 0x03 -> 000 | 011 = 011. According to your docs, you want 100 as the result assuming CRUISE_CONTROL_COMMAND = 000.

2022-11-25 03:30 UTC, Kyle02 commented on projects/steering/src/steering_digital_task.c
> +        set_digital_signal_cruise_control_command(CRUISE_CONTROL_COMMAND |
same issue with the else statement of this case

2022-11-25 03:30 UTC, Kyle02 commented on projects/steering/src/steering_digital_task.c
> +      if (state == GPIO_STATE_HIGH) {
Probably should add an if statement checking to see that CC is on.

2023-01-14 19:18 UTC, mitchellostler reviewed
1. Add gpio_it_register_interrupt for all necessary pins 
2. Read notification value in run_steering_digital_task
3. loop on  event_from_notification to parse each event and use in a case statement

2023-01-25 04:45 UTC, Citrusboa commented on projects/steering/src/steering_digital_task.c
> +  while (event_from_notification(&notification, &steering_event)) {
notify.h library comments updated. 
** any INVALID_EVENT returns STATUS_CODE_INVALID_ARGS in the handle_state_change()

2023-01-25 04:52 UTC, Citrusboa commented on projects/steering/src/steering_digital_task.c
> +  notify_get(&notification);
got it

2023-01-25 04:56 UTC, Citrusboa commented on projects/steering/src/steering_digital_task.c
> +      set_digital_signal_regen_brake_toggle_command(REGEN_BRAKE_COMMAND ^ 1u);
set all gpios to falling edge interrupt settings, besides horn which is rising_falling.

2023-01-26 00:48 UTC, mitchellostler requested changes
Some minor functional changes, a couple nits.
The other thing, is can we change the names of steering_digital_task to steering_digital_input everywhere that it comes up? Since it's not a task, it's kind of a misnomer. 

There's also some changes that need to be made to how we set the events in the can message, but will need to confirm some things at standup today (will add comments when I do)

2023-01-26 00:48 UTC, mitchellostler commented on projects/steering/src/steering_digital_task.c
> +Event steering_event;
should be declared static

2023-01-26 00:48 UTC, mitchellostler commented on projects/steering/src/steering_digital_task.c
> +
Nit: lose the unecessary spacing, just a newline after each break will do

2023-01-26 21:54 UTC, mitchellostler commented on libraries/codegen/boards/steering.yaml
> +    digital_signal:
We really only need to have one message for steering, so just call this one steering_info. 
I think it also makes sense to compress the digital inputs into one U8 (a signal 'digital_input'), with masks for each of the bits depending on what it means. ie, our U8 signal would look like the following where each item is a single bit

```
Messages:
  steering_info:
    id: xx
    target: xx
    signals:
      digital_input: 
        length: 8
```
 
 This digital_input byte will look like: 
 MSB   ->  LSB
 | (X) | (X) | (X) | (X) | (horn_state) |  (regen toggle state) | (cc_toggle_state) | (cc_inc_pressed) | (cc_decr_pressed) |

As this message is sent every cycle, we just need to update it whenever things change.

2023-01-26 22:00 UTC, mitchellostler commented on projects/steering/src/steering_digital_task.c
> +void run_steering_digital_task() {
We should zero the cc_decrease_pressed/cc_increase_pressed bits in the can message on every cycle, since we only want to transmit that that those events have happened once, as opposed to the toggle state messages where we should be broadcasting what the current state is.

2023-01-26 22:03 UTC, mitchellostler commented on projects/steering/src/steering_digital_task.c
> +      set_digital_signal_horn_state(HORN_COMMAND ^ 1u);
Should become set_steering_info_digital_input(DIGITAL_INFO ^ HORN_STATE_MASK) as per comment above

2023-01-26 22:12 UTC, mitchellostler commented on projects/steering/src/steering_digital_task.c
> +    case STEERING_INCREASE_SPEED_EVENT:
This should just set the STEERING_CC_INCREASE_SPEED bit to 1 in the message, you don't need to read it back

2023-02-02 00:48 UTC, mitchellostler reviewed
Just the one change, otherwise looks good

2023-02-02 00:48 UTC, mitchellostler commented on projects/steering/src/steering_digital_task.c
> +      toggle_state =
Hey sorry, this still needs to be fixed. 
If the event occurs, the bit just needs to be set (just `set_steering_info_digital_input(DIGITAL_INPUT | DIGITAL_SIGNAL_CC_INCREASE_MASK)` You don't need to check the state, same goes for the decrease one below.

2023-02-07 21:48 UTC, mitchellostler approved these changes

2023-02-07 21:49 UTC, merged