Add files via upload
uw-midsun/fwxv pull request #136
Opened 2023-02-03 17:40 UTC by wavy152

2023-02-05 03:17 UTC, Kyle02 requested changes

2023-02-05 03:17 UTC, Kyle02 commented on queues/src/main.c
> +      ret = queue_receive(&s_queue1, &outstr[i], 0);
delay ms needs to be 100 otherwise you timeout (can be any amount of time) 100 is just a random num

2023-02-05 03:17 UTC, Kyle02 commented on queues/src/main.c
> +    for (size_t i = 0; i < QUEUE_LEN; i++) {
You almost have it, just need to fix your task2. If you try running it you will get a weird output. You want something like the screenshot I just sent you. Try changing your task2 to try to get your output to match the image. Hint: Think about what you are sending through the queue (and therefore receiving). 
<img width="477" alt="Screen Shot 2023-02-04 at 10 15 47 PM" src="https://user-images.githubusercontent.com/64808590/216799590-44fa87ff-9e33-4c13-b9e8-c51353713bce.png">

2023-02-08 00:48 UTC, mitchellostler reviewed
Looks Good! If you come to the next standup, you can take on a task

2023-02-08 00:48 UTC, closed without merging