Fwxv 152 write max11600 driver
uw-midsun/fwxv pull request #139
Opened 2023-02-04 18:15 UTC by Scrubpai

2023-02-11 20:08 UTC, Bafran approved these changes
Looks good, just minor stuff but it seems like the functionality should work, pending a hardware test. I think @mitchellostler wanted to take a look as well

2023-02-11 20:08 UTC, Bafran commented on projects/pedal/inc/max11600.h
> +static const uint8_t max11600_config_byte = 0b00000101;
Just a minor thing, move these to the config and setup variables to the .c file since these don't need to be used outside of that

2023-02-11 20:08 UTC, Bafran commented on projects/pedal/inc/max11600.h
> +static const uint8_t max11600_write_address = 0b11001000;
And I think read and write addresses can be changed to a #define, also in the .c file, since we don't need to pass the address, just the value.

2023-02-15 02:31 UTC, mitchellostler requested changes
In general, it looks really good. 
A few comments that should be addressed, then we can move it in

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +static const uint8_t max11600_setup_byte = 0b10001000;
These should be #defines, and in hexidecimal form (ie for this one: `#define MAX11600_SETUP_BYTE 0x88`) Also, as adel mentioned move them to the .c file

The comments are great though, keep those. Although it doesn't look like they map directly to the value, am I reading that wrong?

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +#define REFERENCE_VOLTAGE 5
Add units to this (_MV or _V depending on if it's millivolts or volts)

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +// i2c_write(I2C_PORT_1, MAX11600_WRITE_ADDRESS, MAX11600_SETUP_BYTE, 1);
Is there a reason this is here?

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +StatusCode max11600_init(Max11600Storage *Storage, I2CPort i2c_port, I2CAddress i2c_read_address,
Can you add comments for each of the functions stating what they do, and if there's any specific configuration that is needed to call them, or any errors that they may return. Always good practice to document your code as best as possible

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +StatusCode max11600_init(Max11600Storage *Storage, I2CPort i2c_port, I2CAddress i2c_read_address,
Nit: Storage should be fully lowercase everywhere since it's a variable name

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +#ifndef PROJECTS_PEDAL_INC_MAX11600_H_
Use #pragma once and not ifndef

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +  int16_t channel_readings[NUM_MAX11600_CHANNELS];
Is it specified that we get signed values from the sensor? if not we need to make sure that this is a uint.

How are the readings specified? Are they 16 bits? are they signed or unsigned?

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +StatusCode max11600_read_raw(Max11600Storage *Storage);
Pretty important to say that this is updating the same storage readings with either the raw or converted value, since it's not clear from the interface

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/src/max11600.c
> +  Storage->channel_readings[0] *= REFERENCE_VOLTAGE / 256 * 1000;
This is going to be a problem, since this value will just become zero as the value is cast implicitly to an integer in 5 / 256 (no decimal points are stored). If you move the *1000 to the front that should resolve it. You should definitely indicate that the output is in mv in the function description.

2023-02-15 02:31 UTC, mitchellostler commented on projects/pedal/inc/max11600.h
> +#define REFERENCE_VOLTAGE 5
Also, where is this value from?

2023-02-15 02:55 UTC, Bafran commented on projects/pedal/inc/max11600.h
> +  int16_t channel_readings[NUM_MAX11600_CHANNELS];
You're right this should change to a uint8_t, the MAX is 8-bit and since we're in unipolar our readings are unsigned

2023-02-15 02:59 UTC, Bafran commented on projects/pedal/inc/max11600.h
> +static const uint8_t max11600_setup_byte = 0b10001000;
The I2C functions take a pointer to data that's why I thought it'd be best to leave them as variables although not sure what the cleanest way to do that is.

Also just for my own knowledge I thought defining the bytes in binary would be more clear given that each bit serves a specific purpose, is there a reason to keep everything hex?

2023-03-04 19:10 UTC, Bafran approved these changes

2023-03-04 19:12 UTC, mitchellostler approved these changes

2023-03-04 19:12 UTC, merged