sets bits in event group when gpio interrupt is received
uw-midsun/fwxv pull request #15
Opened 2022-02-10 00:54 UTC by ShiCheng-Lu

2022-03-24 01:04 UTC, mitchellostler requested changes
Looks good, a couple of notes and some questions. Sorry this took so long lol

2022-03-24 01:04 UTC, mitchellostler commented on libraries/ms-common/src/x86/gpio_it.c
> +#define NOT_REGISTERED 0xFF
Is this used?

2022-03-24 01:04 UTC, mitchellostler commented on libraries/ms-freertos/inc/FreeRTOSConfig.h
> +#define INCLUDE_xTimerPendFunctionCall 1
Do we use this anywhere?

2022-03-25 01:21 UTC, ShiCheng-Lu commented on libraries/ms-common/src/arm/gpio_it.c
> +  if (address->port >= NUM_GPIO_PORTS || address->pin >= GPIO_PINS_PER_PORT || bit_to_set > 5) {
I think I tried to bit shift by 5 but missed a >, should compare to 32 ie number of bits of task notify.

2022-04-04 23:28 UTC, mitchellostler commented on libraries/ms-common/src/arm/gpio_it.c
>      return status_code(STATUS_CODE_INVALID_ARGS);
Add a check to make sure the scheduler has not yet started:
  ```
if (!(xTaskGetSchedulerState() == taskSCHEDULER_NOT_STARTED)) {
    return STATUS_CODE_UNREACHABLE;
  }
```

2022-04-04 23:28 UTC, mitchellostler commented on libraries/ms-common/src/arm/gpio_it.c
>      return status_code(STATUS_CODE_INVALID_ARGS);
Additionally, when you use the notification library, you can check the input event against `INVALID_EVENT` (defined as 32)

2022-05-04 04:00 UTC, JarvisWeng reviewed
Generally it makes sense. Moving the `edge` to the settings and making `TASK`s into the callbacks.  Only problem I guess if multiple `TASK`s want to catch that GPIO interrupt. But I doubt that's a real concern

2022-05-04 12:57 UTC, ShiCheng-Lu commented on libraries/ms-common/src/arm/gpio_it.c
> +  if (address->port >= NUM_GPIO_PORTS || address->pin >= GPIO_PINS_PER_PORT || bit_to_set > 5) {
this is super out of date? how are you reviewing this version?

2022-05-04 23:08 UTC, JarvisWeng commented on libraries/ms-common/src/arm/gpio_it.c
> +  if (address->port >= NUM_GPIO_PORTS || address->pin >= GPIO_PINS_PER_PORT || bit_to_set > 5) {
Oh I believe I had a previous review for you that I never pressed submit. I'll get rid of this

2022-05-04 23:09 UTC, JarvisWeng commented on libraries/ms-freertos/inc/FreeRTOSConfig.h
> +#define INCLUDE_xEventGroupSetBitFromISR 0
Hm, does it break anything if it's not set to 0? If not then I'm fine with it. We can always set it back later

2022-05-04 23:14 UTC, JarvisWeng commented on libraries/ms-common/test/test_gpio_it.c
> +    notify_get(&triggered);
I think there's needs to be some wrapper for this `notify_get`. Otherwise, users can be using `notify` for multiple things within the `TASK` and they will need to get the `triggered` value. @mitchellostler what do you think?

2022-05-25 00:05 UTC, mitchellostler approved these changes
I'll go ahead and move this through.
Sorry for keeping you in suspense ShiCheng

2022-05-25 00:05 UTC, merged