7seg driver
uw-midsun/fwxv pull request #158
Opened 2023-02-25 06:36 UTC by A3sanjay

2023-03-02 04:01 UTC, JarvisWeng commented on libraries/ms-drivers/seg_display_driver/src/seg_display.c
> +
Could you create a
```
static PincBcd s_bcd_pins = { ..... };
static DispPins s_disp_sel_pins = { ......};
```
Then delete `PinsBcd *bcd_pins, DispPins *disp_sel_pins` from all your function parameters and use the global variables instead.

2023-03-16 01:04 UTC, mitchellostler requested changes
There's quite a few comments, so I'll leave you with these ones to address, and give a second review once you get these done

2023-03-16 01:04 UTC, mitchellostler commented on libraries/ms-drivers/seg_display_driver/src/seg_display.c
> +void set_seg_display(uint8_t disp_value, uint8_t pin_number) {
should take a SegDisplay* display as an argument

2023-03-16 01:04 UTC, mitchellostler commented on libraries/ms-drivers/seg_display_driver/src/seg_display.c
> +  uint8_t A = 1 ? (dec_to_bcd(disp_value) | 1) == dec_to_bcd(disp_value) : 0;
You can make this much cleaner with the following 
```
// Get GPIO values
uint8_t bcd = dec_to_bcd(disp_value);
GpioState state_a = bcd & 0x1;
GpioState state_b = bcd & 0x2;
GpioState state_c = bcd & 0x4;
GpioState state_d = bcd & 0x4;
```
And then just set each of the GPIOs to the value 
````
gpio_set_state(display->A, state_a);
...
```
etc

2023-03-22 22:50 UTC, mitchellostler commented on libraries/ms-drivers/seg_display_driver/inc/seg_display.h
> +StatusCode set_display_set_float(SegDisplay *display, float val);
This should be seg_display instead of set_display at the start

2023-03-22 22:54 UTC, mitchellostler reviewed
Just the one comment, otherwise looks really good.

2023-03-25 17:38 UTC, mitchellostler approved these changes

2023-03-25 17:38 UTC, merged