Fwxv 167 can watchdog
uw-midsun/fwxv pull request #163
Opened 2023-03-13 00:18 UTC by JarvisWeng

2023-03-23 01:28 UTC, ShiCheng-Lu commented on can/src/can.c
> +    clear_tx_struct();
I don't think you should clear data here. expose the function but don't always clear it.

2023-03-23 01:29 UTC, ShiCheng-Lu commented on can/src/can.c
> +    clear_tx_struct();
if you need to clear the received flag, probably best to autogen the setter for that

2023-03-23 01:31 UTC, ShiCheng-Lu commented on libraries/codegen/templates/_rx_all.c.jinja
> +static CanWatchDog s_{{message}}_watchdog = {0, {{message_data["target"][board]["watchdog"] | lower}}};
can you change this to s_{{message}}_msg_watchdog?

2023-03-23 01:34 UTC, ShiCheng-Lu commented on libraries/codegen/boards/new_can.yaml
> +          watchdog: True
why are some of these True/false, some numbers? (this + libraries/codegen/boards/babydriver.yaml)

2023-03-23 01:38 UTC, ShiCheng-Lu commented on libraries/codegen/templates/_rx_all.c.jinja
> +                        s_{{message}}_watchdog.max_cycles);
these two are exactly the same...

2023-03-23 01:40 UTC, ShiCheng-Lu commented on libraries/master/inc/master_task.h
> +Task *get_master_task();
why not use DECLARE_TASK(); here in the header instead of this get_master_task func?

2023-03-23 01:42 UTC, ShiCheng-Lu commented on libraries/master/src/master_task.c
> +#ifdef TEST
is this suppose to be MS_TEST?

2023-04-05 02:46 UTC, ShiCheng-Lu approved these changes
lgtm

2023-04-05 23:39 UTC, mitchellostler requested changes

2023-04-05 23:39 UTC, mitchellostler commented on libraries/master/inc/master_task.h
> +Task *get_master_task();
+1 on this

2023-04-05 23:39 UTC, mitchellostler commented on libraries/master/src/master_task.c
> +    vTaskEndScheduler();
I think this function is not supported on hardware correct? 
Or does it just infinite loop?

We should maybe broadcast a fatal error message too

2023-04-05 23:39 UTC, mitchellostler commented on libraries/codegen/templates/_rx_all.c.jinja
> +        if (s_{{message}}_msg_watchdog.cycles_over >= s_{{message}}_msg_watchdog.max_cycles) {
We're going to need to do something other than log critical here, since we'll need a way of detecting which watchdog has failed so that we can act on it.

2023-04-05 23:39 UTC, mitchellostler commented on libraries/codegen/templates/_rx_all.c.jinja
> +        if (s_{{message}}_msg_watchdog.cycles_over >= s_{{message}}_msg_watchdog.max_cycles) {
We also never reset the watchdog count here if we do receive a message, and we should

2023-04-05 23:39 UTC, mitchellostler commented on libraries/codegen/templates/_rx_all.c.jinja
> +                g_rx_struct.received_{{message}} = true;
We should do this in can hardware no? Right now it looks like we're just setting it every cycle instead of when we actually have a new message that we've pulled of the CAN bus

2023-05-19 20:28 UTC, mitchellostler commented on libraries/codegen/templates/_getters.h.jinja
> +#define get_recevied_{{message}} \
Little typo here

2023-05-19 20:29 UTC, mitchellostler approved these changes
All looks good. 
Do we reset the received_{message} to false though? would make sense to do that in the tx_all I think.

2023-05-20 21:18 UTC, merged