finished max11600 test
uw-midsun/fwxv pull request #168
Opened 2023-03-18 17:12 UTC by Scrubpai

2023-03-18 21:32 UTC, Bafran requested changes

2023-03-18 21:32 UTC, Bafran commented on projects/pedal/test/test_pedal_max11600.c
> +#define THROTTLE_CHANNEL MAX11600_CHANNEL_0
Are these channels definitions needed?

2023-03-18 21:32 UTC, Bafran commented on projects/pedal/test/test_pedal_max11600.c
> +  for (int LSB_THROTTLE = 0; LSB_THROTTLE < 256; LSB_THROTTLE++) {
We don't necessarily need to mock every single possibility, let's just try out maybe 5 values between 0 - 3.3V

2023-03-18 21:32 UTC, Bafran commented on projects/pedal/test/test_pedal_max11600.c
> +        i2c_write(TEST_MAX11600_I2C_PORT, MAX11600_WRITE_ADDRESS, tx_data, 3);
This should be changing soon, we'll have some kind of I2C setter function so we can set a value that will then be read when the i2c_read() function is called.

2023-03-18 21:32 UTC, Bafran commented on projects/pedal/test/test_pedal_max11600.c
> +  for (int LSB_THROTTLE = 0; LSB_THROTTLE < 256; LSB_THROTTLE++) {
Same thing here, we don't need to mock every value.

2023-03-18 21:32 UTC, Bafran commented on projects/pedal/test/test_pedal_max11600.c
> +          TEST_ASSERT_EQUAL(expected_converted_value, max_storage.channel_readings[channel]);
Try run these tests, I ran it on my computer and the asserts were failing for I think both tests, so just make sure that it is actually working. It's also possible that it is in fact the MAX driver failing, in which case we should fix that bug.

2023-04-05 23:46 UTC, mitchellostler reviewed
Just the two things, otherwise looks good!

2023-04-05 23:46 UTC, mitchellostler commented on projects/pedal/src/max11600.c
> +static const I2CSettings i2c_settings = {
This shouldn't be in the driver file, this should be passed from main to max11600 init. Also the driver should be in the ms-drivers library. @Bafran did you fix this on master or was that something else?

2023-04-05 23:46 UTC, mitchellostler commented on projects/pedal/test/test_pedal_max11600.c
> +#define REFERENCE_VOLTAGE_V 3.3
using decimals in a defined macro can create all sorts of problems, change this to mV please. It won't be a problem with how you used it, but is really not good practice

2023-05-19 20:48 UTC, merged