added bts load switch functionality except init function
uw-midsun/fwxv pull request #188
Opened 2023-05-21 14:24 UTC by harsh-patell

2023-05-23 17:06 UTC, mitchellostler requested changes
Overall looks really good, all the logic looks correct. I just added a couple of comments to make the interface a bit cleaner. Also, not sure what the comments are at the end of your header file?

2023-06-08 01:42 UTC, mitchellostler approved these changes

2023-06-08 01:43 UTC, mitchellostler commented on libraries/ms-drivers/inc/bts_load_switch.h
> +  GpioState *select_state_stm32;
This should not be a pointer, it should just be a GpioState. This is what is causing your build failures

2023-06-13 00:14 UTC, harsh-patell commented on libraries/ms-drivers/inc/bts_load_switch.h
> +  GpioState *select_state_stm32;
I made the appropriate change, build is green now

2023-06-15 00:26 UTC, mitchellostler approved these changes

2023-06-15 00:26 UTC, merged