FWXV-214: pd smoke tests
uw-midsun/fwxv pull request #199
Opened 2023-06-25 04:49 UTC by devAdhiraj

2023-07-22 17:49 UTC, JarvisWeng commented on smoke/power_distribution/inc/power_distrbution.h
> +#define FRONT_PD_BOARD
You should make this defined in the `SConstruct`

2023-07-22 17:49 UTC, JarvisWeng commented on smoke/power_distribution/inc/power_distrbution.h
> +  typedef enum {
Put this in a header

2023-07-22 17:49 UTC, JarvisWeng commented on smoke/power_distribution/inc/power_distrbution.h
> +  } Switch;
Same with this enum. Put in a header

2023-08-28 14:27 UTC, JarvisWeng commented on smoke/power_distribution/config.json
> +{
@mitchellostler are we keeping the `power_distribution` project? Or only using `power_distribution_front`?

2023-08-28 14:29 UTC, JarvisWeng commented on smoke/power_distribution/src/main.c
> +    if (!grp) {
You should do `grp == NULL`

2023-08-28 14:30 UTC, JarvisWeng commented on smoke/power_distribution/src/main.c
> +TASK(master_task, TASK_MIN_STACK_SIZE) {
Include `master_task.h` and just init the master task. Also define `run_slow, run_medium, and run_fast` functions

2023-09-01 22:46 UTC, devAdhiraj commented on smoke/power_distribution/src/main.c
> +TASK(master_task, TASK_MIN_STACK_SIZE) {
Done. @JarvisWeng

2023-09-01 22:46 UTC, devAdhiraj commented on smoke/power_distribution/src/main.c
> +    if (!grp) {
Done

2023-09-05 22:27 UTC, mitchellostler reviewed
A few comments, otherwise LGTM!

2023-09-05 22:27 UTC, mitchellostler commented on smoke/power_distribution/config.json
> +{
I think we're fine to just do the power_distribution project for smoke test. This doesn't affect the regular project structure right?

2023-09-05 22:27 UTC, mitchellostler commented on smoke/power_distribution/src/main.c
> +      out_grp = 1;
Out group should start at 0, not 1 right?

2023-09-09 01:15 UTC, devAdhiraj commented on smoke/power_distribution/src/main.c
> +      out_grp = 1;
I started at 1 for now so it skips the ALL output group. I figured if we run it on hardware, it is probably safer to test with a few pins first instead of trying all pins. Once its working on hw, then I think we can change it to 0.

2023-09-09 01:15 UTC, devAdhiraj commented on smoke/power_distribution/inc/power_distrbution.h
Thanks, fixed it.

2023-11-04 14:35 UTC, mitchellostler requested changes
Overall looks good, a couple questions/discussion items. We'll work to get this in today

2023-11-04 14:35 UTC, mitchellostler commented on smoke/power_distribution/config.json
> +{
We just need one power_distribution project. We should talk at standup about what we need to do to remove the functionality for the front/rear pd generation

2023-11-11 01:01 UTC, mitchellostler approved these changes
LGTM. Just fix your merge conflicts

2023-11-11 21:08 UTC, mitchellostler approved these changes

2023-11-13 20:27 UTC, merged