fwxv 228 - temp sense
uw-midsun/fwxv pull request #214
Opened 2023-09-30 18:05 UTC by cnscwong

2023-10-14 18:14 UTC, ShiCheng-Lu requested changes

2023-10-14 18:14 UTC, ShiCheng-Lu commented on projects/solar_sense/src/main.c
> +#define DEVICE_ID 0x04
whats this device id used for?

2023-10-16 01:53 UTC, ShiCheng-Lu commented on projects/solar_sense/src/temp_sense.c
> +  return (MAX_TEMP - MIN_TEMP) * ((voltage_reading - MIN_VOLTS1) / (MAX_VOLTS1 - MIN_VOLTS1));
I guess this is technically fine since MIN_TEMP is 0, otherwise you'll still need to add MIN_TEMP to get the actual temp.

2023-10-16 01:56 UTC, ShiCheng-Lu commented on projects/solar_sense/inc/temp_sense.h
> +uint16_t calculateTempDigital2(uint16_t temp_analog);
these should be private functions since only temp_sense will be using them. you can just remove them from the header file, (and add a prv_ before the function in the .c file to indicate they are private functions)

2023-10-16 01:57 UTC, ShiCheng-Lu approved these changes

2023-11-01 01:23 UTC, JarvisWeng commented on projects/solar_sense/src/temp_sense.c
> +    gpio_get_state(&(temp_sense_pins[TEMP_SENSE_OVERTEMP]), &curr_state);
This will be very fast? Should be in the master_task?

2023-11-07 22:38 UTC, merged