implement max17261 driver
uw-midsun/fwxv pull request #220
Opened 2023-10-11 14:56 UTC by 03predo

2023-10-14 17:19 UTC, JarvisWeng commented on libraries/ms-drivers/inc/max17261_fuel_gauge_defs.h
> +  MAX17261_VOLT_ALRT_THRSH,
Do most of these just increment?

2023-10-14 17:19 UTC, JarvisWeng commented on libraries/ms-drivers/src/max17261_fuel_gauge.c
> +  buf[1] = value & 0x00FF;
I feel like there's a function for swapping endianness.
`#include <byteswap.h>`
though that should be fine, just a nit

2023-10-31 22:39 UTC, mitchellostler requested changes
Overall looks great. Just the one issue with the integer types in the defines. 

I also asked for comments, but if you want to write up some documentation that covers how it's initialized, how normal operation works, and what data we have available, that.would be even better. I've created a page [here] (https://uwmidsun.atlassian.net/l/cp/JLPESZnT) which you can use if you like

2023-10-31 22:39 UTC, mitchellostler commented on libraries/ms-drivers/src/max17261_fuel_gauge.c
> +#define PCT_LSB (1U / 256U)                            // LSBit is 1/256%
This will evaluate to an integer, so will just be zero. 
If you want to do it as float arithmetic, you need to set one of the values as a float (ie 1.0 / 256)
Same goes for values below

2023-10-31 22:39 UTC, mitchellostler commented on libraries/ms-drivers/src/max17261_fuel_gauge.c
> +  buf[1] = value & 0x00FF;
I wouldn't worry about linking in a whole library to do this, this should be fine

2023-10-31 22:39 UTC, mitchellostler commented on libraries/ms-drivers/inc/max17261_fuel_gauge.h
> +StatusCode max17261_get_reg(Max17261Storage *storage, Max17261Registers reg, uint16_t *value);
Can we get comments giving more info on what each of these are returning, and with units :) 
I see that you set the var names to have some of this info, but would be great to have it more verbose.

2023-10-31 22:53 UTC, mitchellostler commented on libraries/ms-drivers/inc/max17261_fuel_gauge_defs.h
> +  MAX17261_VOLT_ALRT_THRSH,
I'm also confused, are there register values that are skipped in between? or are they just ones you deemed we wouldn't use?

2023-10-31 22:53 UTC, mitchellostler commented on libraries/ms-drivers/src/max17261_fuel_gauge.c
> +                                (uint8_t *)&reg8, sizeof(uint8_t)));
Nit: These uint8_t* casts aren't necessary but won't hurt. Usually good to not use casts you don't need though

2023-10-31 22:53 UTC, mitchellostler commented on libraries/ms-drivers/inc/max17261_fuel_gauge.h
> +StatusCode max17261_get_reg(Max17261Storage *storage, Max17261Registers reg, uint16_t *value);
Are we expecting to call these functions directly?
If we're just going to be calling them through the other functions, might as well not include them in the header

2023-11-01 16:26 UTC, 03predo commented on libraries/ms-drivers/inc/max17261_fuel_gauge_defs.h
> +  MAX17261_VOLT_ALRT_THRSH,
Yeah so most of them just increment but some of them are reserved. You can see the reg map on P.27 of this datasheet https://www.analog.com/media/en/technical-documentation/user-guides/max1726x-modelgauge-m5-ez-user-guide.pdf

2023-11-11 20:46 UTC, mitchellostler approved these changes

2023-11-11 20:46 UTC, merged