Added PD fault module
uw-midsun/fwxv pull request #243
Opened 2023-12-06 01:42 UTC by elbertchen1

2024-01-03 21:13 UTC, mitchellostler requested changes

2024-01-06 21:35 UTC, mitchellostler requested changes
Overall looks good! a few comments, and a change needed after a quick discussion with forest, that the threshold monitoring with the ADC can be removed

2024-01-06 21:35 UTC, mitchellostler commented on projects/power_distribution/src/main.c
> +  wait_tasks(1);
You don't want to wait tasks here, since the adc_run call doesn't send to the end task semaphore

2024-01-06 21:35 UTC, mitchellostler commented on projects/power_distribution/src/pd_fault.c
> +#define AUX_OVERCURRENT_THRESHOLD 8000   // Assuming ADC reading is in mA
can you add a units suffix (_MV) at the end of these macros

2024-01-06 21:35 UTC, mitchellostler commented on projects/power_distribution/src/pd_fault.c
> +#define AUX_OVERTEMP_THRESHOLD 60
_DEG_C at the end (if that's what it is)

2024-01-06 21:35 UTC, mitchellostler commented on projects/power_distribution/inc/pin_defs.h
> +#define AUX_OVERCURRENT \
These are available on the schematic, we don't need placeholders

2024-01-06 21:35 UTC, mitchellostler commented on projects/power_distribution/inc/pin_defs.h
> +#define AUX_OVERCURRENT \
Isense is current sense, and vsense is temperature

2024-01-06 21:35 UTC, mitchellostler commented on projects/power_distribution/src/pd_fault.c
> +  double dcdc_temp = (double)dcdc_temp_reading / 1000;
Hey, so I just chatted with Forest. We don't need the detection for the thresholds anymore. We can take out the overcurrent and overtemp functions, along with their fault bit definitions

2024-01-06 23:32 UTC, mitchellostler commented on projects/power_distribution/inc/pin_defs.h
> +#define AUX_OVERCURRENT \
From below, you can remove these pins

2024-01-08 04:12 UTC, elbertchen1 commented on projects/power_distribution/src/pd_fault.c
> +#define AUX_OVERCURRENT_THRESHOLD 8000   // Assuming ADC reading is in mA
_MA?

2024-01-08 17:42 UTC, mitchellostler approved these changes

2024-01-08 17:42 UTC, merged