Cleanup scons mess
uw-midsun/fwxv pull request #246
Opened 2023-12-13 22:11 UTC by ShiCheng-Lu

2023-12-13 22:15 UTC, ShiCheng-Lu commented on SConstruct
> +    help="Specifies target platform. One of 'arm' or 'x86'. Defaults to 'arm' if not provided."
--platform=... is now checked by scons (optparse) to make sure it's either x86 or arm

2023-12-13 22:15 UTC, ShiCheng-Lu commented on SConstruct
> +    help="Specify the target.   e.g. --library=ms-common, --project=leds, --smoke=adc, --python=example",
--library=... / --project=... is now a single option that stores the target in to TARGET.

2023-12-13 22:16 UTC, ShiCheng-Lu commented on SConstruct
>      action='store'
changed the option for create new task to `scons new --project=... --task=task_name`

2023-12-13 22:17 UTC, ShiCheng-Lu commented on SConstruct
> +    help="(x86) Specifies the sanitizer. One of 'asan' for Address sanitizer or 'tsan' for Thread sanitizer. Defaults to none."
sanitizer argument to a choice

2023-12-17 06:04 UTC, ShiCheng-Lu commented on smoke/adc/src/main.c
>  #include <stdio.h>
file formatted, no changes

2024-01-13 18:53 UTC, Kyle02 reviewed
Pausing review at libraries/codegen/generator.py

2024-01-13 18:53 UTC, Kyle02 commented on SConstruct
> +TARGET = GetOption('name')
Does this get the output from set_target?

2024-01-13 18:53 UTC, Kyle02 commented on SConstruct
> +    SConscript('scons/build.scons', exports='VARS')
Are we deleting the build section and moving into this testing area? Do we not need SConscript('scons/build.scons', exports='VARS') for stuff without "test"

2024-01-13 18:53 UTC, Kyle02 commented on SConstruct
> +                            f"python3 scons/mem_report.py build/arm/bin/{TARGET}"))
does TARGET include the /projects/ that was there previously? Or does it not need it anymore

2024-01-13 18:53 UTC, Kyle02 commented on build_system.md
> +targests can be specified with an option.
NIT: "targets"

2024-01-13 18:53 UTC, Kyle02 commented on build_system.md
> +targests can be specified with an option.
Also maybe add a full example for sim and test, since itll easier to just copy paste and fill in the correct project. I think itll be easier for people to see whats going on if theres an example like the previous build_system.md 

e.g `scons sim --project=leds`

2024-01-13 18:53 UTC, Kyle02 commented on libraries/codegen/boards/centre_console.yaml
> +      id: 1
What are the ID changes for?

2024-01-14 02:40 UTC, ShiCheng-Lu commented on SConstruct
> +TARGET = GetOption('name')
yes, destination of '--library', '--project', '--smoke', '--python', '--py', option is "name" and set via the callback  set_target(option, opt, value, parser):, set on line 14

2024-01-14 04:15 UTC, ShiCheng-Lu commented on SConstruct
> +    SConscript('scons/build.scons', exports='VARS')
test.scons now sets up emitters (basically adds a callback whenever a target is defined) this emitter will be called when build.scons defines a target (project or lib, etc.) then look into the directory of the target and add any tests that exists.

2024-01-14 04:15 UTC, ShiCheng-Lu commented on SConstruct
> +                            f"python3 scons/mem_report.py build/arm/bin/{TARGET}"))
target is now the path from root of fwxv, then within the variant dir, it becomes the path relative to build/platform/bin/

2024-01-14 04:24 UTC, ShiCheng-Lu commented on .gitignore
> -*can_codegen.h
these all reside in build/ folder, already ignored

2024-01-14 04:33 UTC, ShiCheng-Lu commented on build_system.md
> +targests can be specified with an option.
done

2024-01-14 04:38 UTC, ShiCheng-Lu commented on libraries/codegen/boards/centre_console.yaml
> +      id: 1
felt like it

2024-01-25 22:05 UTC, JarvisWeng approved these changes

2024-01-25 22:05 UTC, JarvisWeng commented on .gitignore
> -*can_codegen.h
Yeah they weren't before while I was testing. It's fine to get rid of them

2024-01-25 22:05 UTC, JarvisWeng commented on libraries/ms-drivers/inc/ltc6811.h
> +  uint16_t icom0 : 4;
This shouldn't matter right? Since we're putting them to be 4 bits right?

2024-01-26 04:27 UTC, ShiCheng-Lu commented on libraries/ms-drivers/inc/ltc6811.h
> +  uint16_t icom0 : 4;
I believe the compiler was complaining about the uint8_t  d0 : 8; packing 8 bits with 8 bits. since we are only using 4 bits, it doesn't matter as the packed output is the same

2024-01-28 23:51 UTC, Kyle02 requested changes
Have you tried running scons sim yet? I'm trying to run this on a test branch but I'm not able to get scons leds to work.

2024-01-29 00:11 UTC, Kyle02 commented
> Have you tried running scons sim yet? I'm trying to run this on a test branch but I'm not able to get scons leds to work.

We discovered there is an issue with this. I don't think we should merge this until all scons commands have been verified, so shi cheng will be responsible for testing scons flash and other commands

2024-02-01 04:31 UTC, merged