Soft 595 can pack transmit struct
uw-midsun/fwxv pull request #25
Opened 2022-03-05 07:46 UTC by 123Logan321

2022-03-09 04:23 UTC, JarvisWeng requested changes

2022-03-09 04:23 UTC, JarvisWeng commented on libraries/codegen/templates/_pack.h.jinja
> +{% for key in signal%}{%if loop.first %} ({{key}}_u{{signal_length[0]}}){% else %}, ({{key}}_u{{signal_length[0]}}){% endif %}{% endfor-%}{% endset -%}
Indent this for please. It's inside another for

2022-03-09 04:23 UTC, JarvisWeng commented on libraries/codegen/templates/_pack.h.jinja
> +{% set bms_function %}{{message_1}}{{message_2}}{{message_3}}{{message_4}}{% endset -%}
Change this name

2022-03-09 04:23 UTC, JarvisWeng commented on libraries/codegen/templates/_pack.h.jinja
> +{% set message_1 -%}
You should rename all the `message_1, message_2, ...` Those aren't really what they represent and make reading this more confusing

2022-03-09 04:23 UTC, JarvisWeng commented on libraries/codegen/templates/_pack.h.jinja
> +void can_pack_{{message}}(CanMessage *msg_ptr{%- for key in signal-%}, uint{{signal_length[0]}}_t {{key}}_u{{signal_length[0]}}{%- endfor%}){ {%- endset -%}
Try to put the `{%- endset -%}` on a new line. Makes the jinja more readable

2022-03-09 04:23 UTC, JarvisWeng commented on libraries/codegen/generator.py
> +def format_pack_h(env, template_name, file_path, data):
So instead of making a jinja filter, you made this function to format?

2022-03-09 05:23 UTC, 123Logan321 commented on libraries/codegen/generator.py
> +def format_pack_h(env, template_name, file_path, data):
Yeah I thought that is how you would format it, I will fix this error sorry.

2022-03-09 13:23 UTC, JarvisWeng commented on libraries/codegen/generator.py
> +def format_pack_h(env, template_name, file_path, data):
Yeah, I would like it to be a Jinja filter, that way it's more portable between templates if we create more that need it

2022-03-10 01:02 UTC, 123Logan321 commented on libraries/codegen/generator.py
> +def format_pack_h(env, template_name, file_path, data):
ok I will get to fixing the errors, thanks

2022-03-24 00:46 UTC, 123Logan321 commented on libraries/codegen/generator.py
> +            template[i] = "\n" + (" "*(len(template[0]) + len(template[1]) - 9)) + template[i]
Yeah, it is for adding the tabbing space, and template[0] always corresponds to "void" and template[1] is can_pack_name(CanMessage.

2022-03-24 01:44 UTC, JarvisWeng approved these changes

2022-03-24 01:45 UTC, merged