Fixed FSM Timing out in PD
uw-midsun/fwxv pull request #254
Opened 2024-01-18 19:46 UTC by Akashem06

2024-01-23 20:32 UTC, Bafran commented on libraries/ms-common/inc/fsm.h
> +  TASK(name, TASK_STACK_256) {      \
Were there memory issues with this at 512?

2024-01-28 03:27 UTC, mitchellostler requested changes
Just a couple changes, only one functional change. Looks good!

2024-01-28 03:27 UTC, mitchellostler commented on libraries/ms-common/inc/fsm.h
> +  TASK(name, TASK_STACK_256) {      \
Yeah, I believe adhiraj was troubleshooting this. We should make this configurable.

@Akashem06 Can you add a stack size param to the FSM() macro which we will pass to the TASK() macro. I think that reducing the memory size for this may have affects on all the other project FSMs, and it really shouldn't be hardcoded, that doesn't make sense

2024-01-28 03:27 UTC, mitchellostler commented on projects/fsm_demo/src/main.c
> -  delay_ms(1000);
Lets leave this in, unless there's a reason you took it out

2024-01-28 03:27 UTC, mitchellostler commented on projects/power_distribution/src/main.c
> +  i2c_init(I2C_PORT_1, &i2c_settings);
Yeah, I should have caught this on the initial review, my bad

2024-01-28 21:19 UTC, Akashem06 commented on projects/fsm_demo/src/main.c
> -  delay_ms(1000);
I got rid of it because it causes Master task to timeout (any delay > 500ms) It seems like the delay in the medium cycle causes mastertasks xTaskDelayUntil() to return PDFalse. 

I'm not 100% sure why but I think it is because the delay_ms causes the scheduled xTaskDelayUntil() to be in the past, returning PDFault. 

If you could explain it better that would be great!

2024-01-30 19:49 UTC, Bafran commented on projects/fsm_demo/src/main.c
> -  delay_ms(1000);
Yeah I think removing this line is correct since `xDelayUntil` takes care of the cycle time

2024-02-03 21:38 UTC, Bafran commented
Closing this because you said these changes were in your newer PR. If you need to reopen this we can do that

2024-02-03 21:38 UTC, closed without merging