Pd rev2 fixes
uw-midsun/fwxv pull request #258
Opened 2024-01-26 15:31 UTC by Akashem06

2024-01-28 03:40 UTC, mitchellostler requested changes
Just the one change. I saw you also have your Power FSM changes up, but it looks like they're in this PR too. If you address the comments on that PR here, we can merge this one and close the other, or we can merge that one first and then you can resolve conflicts, up to you.

2024-01-28 03:40 UTC, mitchellostler commented on projects/power_distribution/src/lights_fsm.c
> +#define brake_lights()                                        \
Not a huge fan of this syntax. I think it would be better to just make it a short prv_ function

2024-02-03 21:37 UTC, Bafran commented on projects/power_distribution/src/power_seq_fsm.c
> -  if (power_context.target_state == POWER_STATE_OFF) {
why did this logic get removed?

2024-02-03 23:39 UTC, mitchellostler approved these changes

2024-02-03 23:39 UTC, merged