Hw timer
uw-midsun/fwxv pull request #259
Opened 2024-02-01 03:50 UTC by Akashem06

2024-02-03 22:11 UTC, Bafran commented on libraries/ms-common/src/arm/hw_timer.c
> +void hw_timer_delay_us(uint32_t us) {
So, a possible issue with this is if a task delays for say 2ms, then gets pre empted by a task that delays for 1ms, the higher priority task would reset the timer, complete its delay, and then when the original task takes over, the timer would be disabled. I'm not 100% sure what the best fix for this is but I'll have to think about that

2024-02-03 22:11 UTC, Bafran commented on smoke/hw_timer/src/main.c
> +    hw_timer_delay_ms(100);
Kind of a nitpick, I'd say test a shorter delay like 300us. It better reflects the use case of a module like this. I think you said you'd previously tested that though

2024-02-04 00:16 UTC, Akashem06 commented on smoke/hw_timer/src/main.c
> +    hw_timer_delay_ms(100);
I tested with 10us and it worked, but I can change the smoke tests delay

2024-02-07 22:19 UTC, JarvisWeng commented on libraries/ms-common/src/arm/hw_timer.c
> +void hw_timer_delay_us(uint32_t us) {
Would it? TIM_GetCounter should be an atomic call. So the unless it happens before `start_count`, it wouldn't be an issue right?
If that's the case, we could critical section this part until later

2024-02-08 02:14 UTC, Bafran requested changes
almost lgtm

2024-02-08 02:14 UTC, Bafran commented on libraries/ms-common/src/arm/hw_timer.c
> +  TIM_Cmd(TIM2, DISABLE);
Add a function for init and enable the timer

2024-03-11 18:54 UTC, Bafran commented
Does this still need the change for timer compare?

http://stm32.kosyak.info/doc/group___t_i_m___exported___functions.html#gab3a6031f187cb8af62eb09a67b4fd2ad

2024-04-23 19:40 UTC, closed without merging