Update can_boards.h.jinja template to create message ids defines
uw-midsun/fwxv pull request #27
Opened 2022-03-05 18:28 UTC by AdrianJendo

Can test with
`python3 libraries/codegen/generator.py -y libraries/codegen/boards/boards.yaml -t libraries/codegen/templates/can_board_ids.h.jinja`
and
`python3 libraries/codegen/generator.py -t libraries/codegen/templates/system_can.dbc.jinja`
to confirm output is correct

2022-03-09 04:09 UTC, JarvisWeng requested changes

2022-03-09 04:09 UTC, JarvisWeng commented on libraries/codegen/templates/can_board_ids.h.jinja
> +#define SYSTEM_CAN_MESSAGE_BPS_HEARTBEAT \
Sorry, these names need to be autogenerated not hard coded.
They will be the names of the
```
SYSTEM_CAN_MESSAGE_<message name>
(<signal name> << 5) + SYSTEM_CAN_DEVICE_<board>
```
Something like this

2022-03-12 08:23 UTC, AdrianJendo commented on libraries/codegen/templates/can_board_ids.h.jinja
> +#define SYSTEM_CAN_MESSAGE_BPS_HEARTBEAT \
Might still be wrong, but let me know if it's on the right track

2022-03-12 17:06 UTC, JarvisWeng commented on libraries/codegen/generator.py
> +    for can_board_id, board in enumerate(master_data["Boards"]):
Might want to make `can_board_id` + 1. Not sure if we want to start at 0. But that's ok for now

2022-03-12 17:06 UTC, JarvisWeng commented on libraries/codegen/templates/can_board_ids.h.jinja
> +{%- for board in boards -%}
All this needs to be below line 23. Since we want `SYSTEM_CAN_DEVICE....` and that's only defined below. Also just move the `#include` back at the top

2022-03-12 17:47 UTC, AdrianJendo commented on libraries/codegen/generator.py
> +    for can_board_id, board in enumerate(master_data["Boards"]):
Would you prefer I change it still?

2022-03-12 17:48 UTC, JarvisWeng commented on libraries/codegen/generator.py
> +    for can_board_id, board in enumerate(master_data["Boards"]):
No that's ok. I'll change it later if its an issue

2022-03-12 17:58 UTC, JarvisWeng approved these changes

2022-03-12 17:58 UTC, merged