ported CI from make to scons
uw-midsun/fwxv pull request #3
Opened 2022-01-22 20:17 UTC by ShiCheng-Lu

2022-01-22 23:15 UTC, ShiCheng-Lu commented
I added a `--define` option to scons, not sure now we want to have that but right now it just plops it down in the build.

2022-01-29 16:19 UTC, ryandancy requested changes

2022-01-29 16:19 UTC, ryandancy commented on .github/workflows/make_dbc_release.yml
> +
The DBC-releaser script is a) out of date (it's on ubuntu-16.04 which doesn't work anymore on GitHub Actions) and b) won't be useful for a while since we don't have a DBC-generation script yet. So I'd say we can just remove it for now, that way we don't have script-failed-to-run errors.

2022-01-29 16:19 UTC, ryandancy commented on .github/workflows/main.yml
> +      #       core.setFailed() // Fail on uncommitted changed
Same with this, I'm not entirely sure if it'll be applicable in the new CAN implementation anyways so we can just remove the post-a-PR-comment-on-uncommitted-changes stuff for now. We can always paste it back over from firmware_xiv if necessary. (This also includes removing the uncommitted-codegen-changes.md file.)

2022-01-29 16:19 UTC, ryandancy commented on .github/workflows/main.yml
> +      #     make pylint
Format and lint is coming soon (Daniel Qu has a PR up for it) so I think it's fine to leave this commented for now, if that PR gets merged before this one then we can uncomment it / set CI up to run format/lint. But we should remove the lint.py file since the other PR will add it and we don't want merge conflicts.

2022-01-29 16:19 UTC, ryandancy commented on .github/workflows/main.yml
> +    branches: [master]
`master` is renamed to `main` in FWXV

2022-02-09 04:08 UTC, ryandancy approved these changes

2022-02-09 04:08 UTC, merged