Soft 605 log library
uw-midsun/fwxv pull request #30
Opened 2022-03-12 05:43 UTC by Kyle02

Not yet ready to merge, still need to add tests. Just setting up a pr for comments on the implementation.

2022-03-12 16:04 UTC, mitchellostler requested changes
Looks really good! I might have gone a bit overboard with the comments, but almost everything is superficial, all the core structure is great. 

You'll need to rebase on master, and I'll get the queue library merged so you can use that in this program as well.

2022-03-12 16:04 UTC, mitchellostler commented on libraries/core/src/log.c
> +static uint8_t s_log_array[QUEUE_LENGTH * ITEM_SIZE] = {0};
the `= {0}` here is redundant, static declarations already zero the memory.

2022-03-12 16:05 UTC, mitchellostler commented
There's also this merge conflict that you'll have to resolve, but I don't think it will be a tough fix.

2022-03-12 19:51 UTC, Kyle02 commented on libraries/core/inc/log.h
> +    else{                                                                                                               \
it seems that scons format does catch format errors in macros, which is good to know

2022-03-15 22:08 UTC, ShiCheng-Lu commented on libraries/ms-common/inc/log.h
> +extern char g_buffer[MAX_LOG_SIZE];
I'd suggest renaming this to g_log_buffer just in case we have other global buffers.

2022-03-16 00:11 UTC, ShiCheng-Lu commented on libraries/ms-common/src/log.c
> +  char rx_buffer[MAX_LOG_SIZE];
I think it's better for this rx_buffer to be static so the compiler knows how much space our program is using. I'm not sure how it works exactly if it can be static in function, static at top level, or left like this. (ask Mitchell or Ryan I'm sure one of them knows).

2022-03-16 00:11 UTC, ShiCheng-Lu commented on libraries/ms-common/src/log.c
> +      if (xQueueReceive(g_log_queue, (rx_buffer), (TickType_t)0)) {
why not just xQueueReceive with a long time instead of checking MessagesWaiting != 0?

2022-03-21 20:25 UTC, mitchellostler commented on libraries/ms-common/src/log.c
> +  char rx_buffer[MAX_LOG_SIZE];
It can be static at top level, or static in the function. Either is fine, and mean the memory will only be initialized once. I think it could be a good idea to leave it in the function here, since it isn't used anywhere else.

2022-03-26 20:34 UTC, mitchellostler commented on libraries/ms-common/inc/log.h
> +extern QueueHandle_t g_log_queue;
Add comment for global handle `global queue handle used in all log calls` or something like that

2022-03-26 20:34 UTC, mitchellostler commented on libraries/ms-common/src/log.c
> +// Holds the queue object (either make this into the task or put the variables in header so task can
This comment is a bit weird. Maybe just say `queue handle definition`

2022-04-02 19:33 UTC, mitchellostler approved these changes

2022-04-02 19:33 UTC, merged