Fwxv 74 queues library tests
uw-midsun/fwxv pull request #38
Opened 2022-03-31 02:29 UTC by Bafran

2022-04-04 00:58 UTC, JarvisWeng requested changes

2022-04-04 00:58 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +static const uint8_t s_list[LIST_SIZE] = {
Nit: Put all on 1 line

2022-04-04 00:58 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +static StaticQueue_t s_queue;
Why do you declare these variables?

2022-04-04 00:58 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +  queue.handle = s_queue_handle;
You're misunderstanding the usage of the `queues.h` You shouldn't set the handler or queue. Only the item size, num of items and storage pointer.

2022-04-04 00:58 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +      if (++index == 5) {
Nit: Replace 5 with `QUEUE_LENGTH`

2022-04-04 00:58 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +      LOG_DEBUG("Received int: %d at tick %lu\n", outstr, tick_count);
Logs are ok for debugging, but you should use `TEST_ASSERT_TRUE` or something to test this out

2022-04-04 00:58 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +        LOG_DEBUG("Failed to peek at tick %lu\n", tick_count);
Again use `TEST_ASSERT`s

2022-04-04 00:58 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +TASK_TEST(test_running_task, TASK_STACK_512) {
In this test, you should be asserting the QUEUE contents, not the status. Probably be easier in the `receiveMessages` task or peek instead.

2022-04-10 20:15 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +      if (status==STATUS_CODE_OK)
Enclose this properly. What do this single line `if` suppose to do?

2022-04-10 20:15 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +        TEST_ASSERT_EQUAL_UINT8_ARRAY(s_list, recv_str, QUEUE_LENGTH);
You should assert the contents regardless if status is not `STATUS_CODE_OK`. In fact, under normal circumstances, it will never go into this `if` statement. Since it `status != STATUS_CODE_OK` will only happen if it doesn't receive. So the recv str, should be different anyway

2022-04-10 20:15 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +        TEST_ASSERT_EQUAL_UINT8(5, outstr);
Why's it always 5?

2022-04-27 01:39 UTC, JarvisWeng commented on libraries/ms-common/test/test_queues.c
> +      TEST_ASSERT_EQUAL_UINT8(outstr, s_list[index]);
Shouldn't this assert be in an `else`?

2022-04-27 23:13 UTC, Bafran commented on libraries/ms-common/test/test_queues.c
> +      TEST_ASSERT_EQUAL_UINT8(outstr, s_list[index]);
I've used a continue in the previous if statement which makes sure it's reading the correct status, but I'll change it to an else to make it more readable.

2022-04-28 23:20 UTC, JarvisWeng approved these changes

2022-04-28 23:20 UTC, merged