Soft 601 delay port
uw-midsun/fwxv pull request #5
Opened 2022-01-23 21:29 UTC by Bafran

2022-01-26 17:34 UTC, ShiCheng-Lu commented
since FreeRTOS only has delay for ms precision, we might want to remove delay_us and call taskDelay from delay_ms. Most delay calls from our projects are ms anyway and this saves from multiplying and dividing by 1000.

2022-01-26 17:35 UTC, ShiCheng-Lu commented on libraries/ms-common/inc/x86/delay.h
> +#include "task.h"
these include headers should be in the implementation file instead of header file, as they are not referenced at all in the header.

2022-01-27 00:24 UTC, mitchellostler commented on libraries/ms-common/src/x86/delay.c
> +  const TickType_t xDelay = t / portTICK_PERIOD_MS;
You can use the method pdMS_TO_TICKS() defined by freeRTOS here, because it will be the most optimized. You also probably don't need to create a new variable, and just return  `vTaskDelay(pdMS_TO_TICKS(t))` directly.

2022-01-27 00:25 UTC, ryandancy reviewed
Seems everyone is reviewing this PR at once - I'll just jump in with a couple of nitpicks.

2022-01-27 00:25 UTC, ryandancy commented on libraries/ms-common/src/x86/delay.c
> +#include "delay.h"
Nitpick: in an implementation file we generally put the corresponding header first on a line on its own, so you'd put `delay.h` first here.

2022-01-27 00:25 UTC, ryandancy commented on libraries/FreeRTOS/src/tasks.c
> -
We probably shouldn't change the FreeRTOS source so we know we haven't made custom modifications if/when we upgrade, so this should be reverted.

2022-01-27 00:25 UTC, ryandancy commented on libraries/core/config.json
> +  }
Nitpick: the indentation here. We probably won't have autoformatting for JSON files so I'd prefer this to be consistent, and we use 2 space indents everywhere else, so let's use 2 space indents consistently here.

2022-01-27 00:30 UTC, mitchellostler commented on libraries/ms-common/inc/x86/delay.h
> +#pragma once
I noticed that this is placed in the x86 Library, but this should be the same for both stm and x86. I think you can move these out to the inc and src folders respectively, unless Ryan has told you differently

2022-01-27 00:32 UTC, ryandancy commented on libraries/ms-common/inc/x86/delay.h
> +#pragma once
Yep this can go in `inc` and `src`, doesn't need to be platform-specific. One of the nice things with FreeRTOS is we have a Linux simulator for it so we can run the same code on x86 and arm/stm32 a lot of the time.

2022-01-27 00:33 UTC, mitchellostler commented on libraries/ms-common/inc/x86/delay.h
> +//
Would also be a good idea to specify that this can only be called in a task, and that calling in main/initialize functions will cause undefined behaviour.

2022-01-27 00:34 UTC, mitchellostler requested changes
Looks good, just a few improvements. Let me know if you have any questions

2022-02-01 02:10 UTC, mitchellostler approved these changes

2022-02-01 02:11 UTC, merged