SOFT-602: Add scons lint and format targets
uw-midsun/fwxv pull request #6
Opened 2022-01-26 06:03 UTC by danielq987

## Feature
Ported over linting (`lint.py` for c files, `pylint` for python) and formatting (`clang-format` for c files, `autopep8` for python) to scons.

Commands used are the same as `firmware_xiv`.

## Code Changes
not done yet

## Potential Issues

2022-01-26 06:32 UTC, danielq987 commented on SConstruct
> +        'no_lint': False,
I'm wondering if we need both a `no_lint` and `no_format` config param. Will there be a case where the two params will be different?

2022-01-26 06:36 UTC, danielq987 commented on SConstruct
> +    return glob.glob('{}/**/*.py'.format(str(dir)), recursive=True)
Using Python globbing is a bit out of place here, but I couldn't find a way to glob using Scons recursively.

2022-01-29 15:57 UTC, ryandancy requested changes
Great job Daniel!

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +        'no_lint': False,
Good point - I don't think there is a case where we'd want to control format and lint separately. Feel free to combine them into one param.

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +PYTHON_DIRS = []
Leaving `PYTHON_DIRS` empty like this is fine for now, but @vaaranan-y when you add the `py` directory you should also change `PYTHON_DIRS` to be set in the directory setup section of this file like `PROJ_DIRS` and `LIB_DIRS`.

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +CLANG_FORMAT_CONFIG = '-i style=file'
Copy the .clang-format file from firmware_xiv into the root of fwxv, then clang-format will format the same in the new repo. (Also, I believe it's `-style=file`.)

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +        py_lint_files += py_files
We should support only formatting/linting a certain project or library using `--project=X` or `--library=X` - currently we always format/lint everything every time but it would be nice to limit that.

Also, since this is on the top level, it's run every time the SConstruct is read (i.e. on every command, even if it's not a lint or format command) - is it possible to move it to a function you call from `run_lint` and `run_format` so that we're not adding overhead to other commands?

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +    print('Done Formatting.')
Instead of using shell tricks with `xargs` to run clang-format/lint/pylint for multiple directories, could you just loop over it in Python? It'll be more robust to different shells that way.

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +    subprocess.run(format_cmd, shell=True)
This seems to print out `No such file or directory` for some reason, maybe it's best to just suppress stdout/stderr for this command?

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +    lint_cmd = 'echo {} | xargs -r python2 ./lint.py'.format(dir_list_to_str(lint_files))
This prints out `Ignoring libraries/stm32f0xx/src/startup_stm32f072.s; not a valid file name (c, cc, h, cpp, cu, cuh)` for me, so we're extraneously including `startup_stm32f072.s` in `lint_files`. Could you filter it to only include `*.[ch]` files?

2022-01-29 15:57 UTC, ryandancy commented on SConstruct
> +    pylint_cmd = 'echo {} | xargs -r pylint'.format(dir_list_to_str(py_lint_files))
In MSXIV we had a list of disabled pylint inspections (in `PYLINT_DISABLE` in the Makefile). We should have a way to disable certain pylint inspections globally in MSXV too. I suggest storing the pylint config in a file called `.pylintrc` and using the `--rcfile` option to load it; that way we don't have to maintain a list of disabled inspections in the middle of the SConstruct.

2022-02-05 07:46 UTC, danielq987 commented on SConstruct
> +        'no_lint': False,
I've merged them, under the name `no_lint`

2022-02-05 15:19 UTC, ryandancy approved these changes

2022-02-05 15:21 UTC, merged