FWXV-96 Created wait_tasks() and send_task_end()
uw-midsun/fwxv pull request #60
Opened 2022-06-15 04:56 UTC by XiZhu0204

2022-06-15 05:00 UTC, XiZhu0204 commented
This build will fail until 95 is merged so that the semaphore handle exists.

2022-06-22 18:45 UTC, mitchellostler requested changes
Good work, this looks great! I added a few comments which should be addressed.
Also, just so you know there's most likely going to be some merge conflicts when Abigail's PR gets merged after she addresses my comments. 

Do you have experience rebasing and resolving merge conflicts, or is this something that you need me to walk you through?

2022-06-22 18:45 UTC, mitchellostler commented on libraries/ms-common/inc/tasks.h
> +#define WAIT_TASK_TIMEOUT portMAX_DELAY
Change this to WAIT_TASK_TIMEOUT_MS and set it to 1000
No task cycle execution should be taking on the order of a second to complete, so we'll use this value for now

2022-06-22 18:45 UTC, mitchellostler commented on libraries/ms-common/inc/tasks.h
> +StatusCode send_task_end();
Specify the parameter as `void`. This means that it will throw a compilation error if any arguments are passed

2022-06-22 18:45 UTC, mitchellostler commented on libraries/ms-common/inc/tasks.h
> +// Waits for the defined number of tasks by repeatedly taking from semaphore that many times
Just make this a one-line comment:
```
// Attempts to take num_tasks items from end task semaphore, indicating the number of tasks completed
// Returns STATUS_CODE_TIMEOUT if timeout occurs, STATUS_CODE_OK if num_tasks items taken successfully
```

2022-06-22 18:45 UTC, mitchellostler commented on libraries/ms-common/src/tasks.c
> +  if (xSemaphoreGive(s_end_task_sem) != pdTRUE) {
Log critical an error message here:
We should never run out of buffer space, this means that we've programmed our project wrong.

2022-06-22 18:45 UTC, mitchellostler commented on libraries/ms-common/src/tasks.c
> +    if (xSemaphoreTake(s_end_task_sem, WAIT_TASK_TIMEOUT) != pdTRUE) {
Use the pdMS_TO_TICKS() macro with our WAIT_TASK_TIMEOUT_MS value

2022-06-22 18:45 UTC, mitchellostler commented on libraries/ms-common/src/tasks.c
> +      // We should never actually return a timeout status code
Remove these comments

2022-06-25 14:10 UTC, mitchellostler approved these changes
Looks good, thanks for completing this!

2022-06-25 14:10 UTC, merged