Add 'new' target
uw-midsun/fwxv pull request #7
Opened 2022-01-29 03:17 UTC by danielq987

2022-01-29 03:25 UTC, danielq987 commented on new_target.py
> +#!/usr/bin/env python3
in firmware_xiv, this file was in a subdirectory `/make`. should that directory exist in fwxv?

2022-01-29 03:25 UTC, danielq987 commented on new_target.py
> +RULES_TEMPLATE = Template("""\
is `rules.mk` still necessary with the scons buildsystem? im guessing no

2022-01-29 03:25 UTC, danielq987 commented on SConstruct
> +    if entry and tests.get(entry):
this check is included so that `scons new` doesn't error out... 
although, I'm not sure why the test command is still being called with `scons new`... seems to have something to do with the Depends(...) statement on line 254

2022-02-05 15:22 UTC, ryandancy commented on new_target.py
> +#!/usr/bin/env python3
You could put it in a `scons` directory, might be a good place for lint.py too.

2022-02-05 15:34 UTC, ryandancy requested changes
Looks great, just a couple nitpicks about documentation and the like.

2022-02-05 15:34 UTC, ryandancy commented on new_target.py
> +    where rules.mk is required for the project or library to be valid.
Update this documentation since we're no longer using `rules.mk`.

2022-02-05 15:34 UTC, ryandancy commented on new_target.py
> +    config = {"libs": deps}
So it's not buried in the middle of a function, you might want to factor out this into a `generate_config` function since it's important and might get frequently modified.

2022-02-05 15:34 UTC, ryandancy commented on SConstruct
> +        raise ValueError("Missing project or library name. Expected --project=... or --library=...")
It would give a nicer error message to just print out this error and then `sys.exit(1)` - raising an exception gives a stack trace that the user shouldn't have to parse through.

2022-02-05 15:34 UTC, ryandancy commented on SConstruct
> +    if entry and tests.get(entry):
Looks like `get_test_list()` is being called regardless of whether the test command is called or not, because it's called in the top-level `Depends` call. This is an ok solution.

2022-02-05 15:35 UTC, ryandancy commented
Also, could you resolve the merge conflicts from the other PR that just got merged?

2022-02-05 18:22 UTC, ryandancy commented on new_target.py
> +    where rules.mk is required for the project or library to be valid.
Update this line too

2022-02-10 02:36 UTC, ryandancy approved these changes

2022-02-10 02:37 UTC, merged