FW103 Homework
uw-midsun/fwxv pull request #75
Opened 2022-07-16 01:24 UTC by elbertchen1

FW103 Homework by Elbert Chen

2022-07-20 22:30 UTC, mitchellostler commented on projects/FW_103/src/main.c
> +      for (int count1 = 0; count1 < ITEM_SZ - 1; count1++)
For future reference, you don't need to do this. You can just pass the s_list index itself instead of copying the word over

2022-07-20 22:32 UTC, mitchellostler commented on projects/FW_103/src/main.c
> +    ret = queue_receive(&s_queue1, &s_queue1_buf, 1000);
You should not be receiving the data to here. This will break your queue, as the array you are passing is already used as memory for the queue itself. You should be using the char array that is provided with the size of the word. (top of task)

2022-07-20 22:34 UTC, mitchellostler requested changes
Hey Elbert, there is only one major issue with your implementation, but otherwise looks good. Were you able to run the code for the queues task? 

Anyways, if you could fix it and push your changes that would be great

2022-07-20 22:38 UTC, mitchellostler requested changes
Hey Elbert, there is only one major issue with your implementation, but otherwise looks good. Were you able to run the code for the queues task? 

Anyways, if you could fix it and push your changes that would be great

2022-07-21 23:51 UTC, elbertchen1 commented
Hey Mitchell, I made the changes you requested. Thanks!

2022-07-23 18:05 UTC, mitchellostler reviewed
Looks good!

2022-07-23 18:06 UTC, closed without merging